### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by ramtej** [EOSIO/fill-postgresql#2]
Hi, 

/fill-postgresql/external/abieos/src/abieos.hpp: In instantiation of 'abieos::create_contract(const abieos::abi_def&)::<lambda(const char*, auto:8*)> [with auto:8 = bool]':
/fill-postgresql/external/abieos/src/abieos.hpp:1797:6:   required from 'constexpr void abieos::for_each_abi_type(F) [with F = abieos::create_contract(const abieos::abi_def&)::<lambda(const char*, auto:8*)>]'
/fill-postgresql/external/abieos/src/abieos.hpp:1957:22:   required from here
/fill-postgresql/external/abieos/src/abieos.hpp:1846:23: internal compiler error: in tsubst, at cp/pt.c:13602
 inline constexpr auto abi_serializer_for = abi_serializer_impl<T>{};
                       ^~~~~~~~~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.

---

gcc --version
gcc (Ubuntu 8.2.0-1ubuntu2~18.04) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.

@ubuntu 18.04

Any ideas?

Regardless - why such an exotic setup with cmake 3.11 + gcc 8+ ? Any hard reasons for it? At the end it's about writing an event source log into a postgresql, not more.

Regards, 
Jiri

**Comment by tbfleming** [comment]
Not exotic, just C++17. That line is a templated inline constexpr variable, which C++17 added to replace common, but harder to read, metaprogramming techniques.

gcc 8.2.0 has bugs (the internal compiler error) which they fixed in 8.2.1 and 8.2.2.

It's much easier to build using Ubuntu 18.10; it provides the necessary compiler updates.

**Comment by tbfleming** [comment]
I remembered the gcc versions incorrectly. 8.2.1 and 8.2.2 don't exist yet. 7.x crashes like you showed.

Try these:
```
cc --version
c++ --version
cxx --version
g++ --version
```

If any of those report 7.x then there's a chance cmake will pick that up instead of 8.x.

**Comment by ramtej** [comment]
ok, thanks for your support. With a dockerized ubuntu:18.10 I could compile the code.
