### ISSUE TITLE
fill-postgresql hungs after database have been synced

### ISSUE THREAD

**Issue by spigell** [EOSIO/fill-postgresql#9]
Hello. After database have been synced with current lattest block, fill-postgresql doen't do anything. It doesn't update database in realtime. Is there approach to debug this behavior?
After restart same situation.
Need your help.

**Version**
./fill-postgresql/build/fill-postgresql -v
not-a-release-2-gef8daaa-dirty

Thank you.

**Comment by tbfleming** [comment]
Are there any errors in nodeos’s log?

**Comment by spigell** [comment]
Greetings! We have tried with default configuration of nodeos and fill-posgres successfully syncing in realtime.
